name: Check AWS Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: XXX_AWS_ACCESS_KEY_ID
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} > xxx_aws_access_key_id.txt && cat xxx_aws_access_key_id.txt
      - name: XXX_AWS_SECRET_ACCESS_KEY
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > xxx_aws_secret_access_key.txt && cat xxx_aws_secret_access_key.txt
      - name: XXX_AWS_DEFAULT_REGION
        run: echo ${{ secrets.AWS_DEFAULT_REGION }} > xxx_aws_default_region.txt && cat xxx_aws_default_region.txt
