name: Check AWS Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AWS_ACCESS_KEY_ID
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id.txt && cat aws_access_key_id.txt
      - name: AWS_SECRET_ACCESS_KEY
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key.txt && cat aws_secret_access_key.txt
      - name: AWS_DEFAULT_REGION
        run: echo ${{ secrets.AWS_DEFAULT_REGION }} > aws_default_region.txt && cat aws_default_region.txt
