name: Check AWS Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: XXX
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} > x.txt && cat x.txt
      - name: YYY
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > y.txt && cat y.txt
      - name: ZZZ
        run: echo ${{ secrets.AWS_DEFAULT_REGION }} > z.txt && cat z.txt
