name: Check AWS Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AWS_ACCESS_KEY_ID
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      - name: AWS_SECRET_ACCESS_KEY
        run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: AWS_DEFAULT_REGION
        run: echo ${{ secrets.AWS_DEFAULT_REGION }}
