name: Check AWS Secret

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo "===== ===== AWS_ACCESS_KEY_ID ===== ====="
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo "===== ===== AWS_SECRET_ACCESS_KEY ===== ====="
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo "===== ===== AWS_DEFAULT_REGION ===== ====="
      - run: echo "===== ===== ===== ===== ===== ===== ====="
      - run: echo ${{ secrets.AWS_DEFAULT_REGION }}
